rootfs-postcommands: Remove spaces before ; in -ROOTFS_..._COMMAND
With spaces in ROOTFS_POSTPROCESS_COMMAND attempts to remove elements
using ROOTFS_POSTPROCESS_COMMAND_remove causes parse failures of the
form:

  bb.pysh.sherrors.ShellSyntaxError: LexToken(COMMA,';',0,0)
  followed by:
    LexToken(TOKEN,'write_image_test_data',0,0)
    LexToken(COMMA,';',0,0)
    LexToken(TOKEN,'set_systemd_default_target',0,0)
    LexToken(COMMA,';',0,0)
    LexToken(TOKEN,'systemd_create_users',0,0)

Removing the spaces between the function name and semicolon allows the
list to parse correctly.

(From OE-Core rev: c6ab64d6b77c70f00264c162330362a7feb06463)

Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>